### PR TITLE
Add compatibility filtering

### PR DESCRIPTION
**Pull request by BynariStar**
Implemented the ability to filter games by their compatibility rating.

Gif:
recording

### CODE REVIEW

**Comment by chris062689** [comment]
Looks good aside from a minor nitpick. Can you also run this through a linter to format the javascript code? Thanks.

**Comment by BynariStar** [comment]
You clear the filter by clicking on the active filter again. What linter do you recommend? They all produce different results.

**Comment by chris062689** [comment]
In addition, I'd have a button perhaps floating at the top right of that says "Clear".

**Comment by BynariStar** [comment]
New clear button:
image

**Comment by chris062689** [comment]
Can we place the clear button above the bars with padding?

**Comment by BynariStar** [comment]
Not really. Since it's an SVG, you can't place the button outside of its boundaries. You'd have to expand the SVG, and I'm not sure how simple that is with Highcharts.

**Comment by chris062689** [comment]
Okay, if not already, let's have that "Clear" button only be visible when there is a filter, can we also rename it to "Clear Filter"? 

Other than the pending discussion, LGTM.

**Comment by BynariStar** [comment]
It already automatically clears. Are you referring to the map? I wasn't sure how to get the ratings otherwise.

**Comment by chris062689** [comment]
I commented on the block of code, basically we don't want to hard code the array.
Please use hugo's syntax to create the array from the data file.

An example was shown below in the comment.

**Comment by BynariStar** [comment]
Found a simple solution. Should be good now.

**Pull request merged**
