### PR TITLE
Change Bleeding Edge to Canary (I do not know HTML or JS: v)

### PR DESCRIPTION
**Pull request by acnleditor2**

### CODE REVIEW

**Comment by jroweboy** [comment]
We've got a whole new installer in the works that will install both nightly and canary and keep them both up to date as well. As such, this entire page will be redesigned very shortly. The effort is appreciated, but won't really do much after the new installer goes live :)

**Comment by j-selby** [comment]
We are working on redesigning our downloads page as we speak. This issue will be solved when that is pushed.

**Comment by chris062689** [comment]
Thanks for contributing! We'll have a new downloads page up (hopefully!) soon.

**Comment by chris062689** [comment]
We'll go ahead and deploy this change, since Bleeding Edge is over 2 months old now.

**Pull request merged**
